# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-18 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("borg", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="path",
            field=models.CharField(default="/var/lib/borg", max_length=128),
        )
    ]
