# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-05 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borg', '0004_auto_20200220_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='append_only',
            field=models.BooleanField(default=False, help_text=''),
        ),
    ]
